

all:
	echo "All"
	python modular_if_cond_exp.py
	python modular_if_cond_exp2.py



clean:
	rm -f *.dot *.xml *.pyc *.png *.pdf *testOutput.txt *.mod
	rm -rf nineml_mechanisms/
	rm -rf out/
	rm -rf Results
	rm -rf i686/
	rm -rf cond_parse_Calc_parsetab.py*
	rm -rf expr_parse_Calc_parsetab.py*
