# A demo comparison of native stdp_synapse and the stdp_guetig_9ml
# model generated by 9ML code generation with python lib9ml

# Author: Abigail Morrison & Susanne Kunkel, 2011
# on the basis of Eilif Muller's comparison9ml_iaf_cond_exp.py

# See: README for the build process for the "MyModule" required
# by nest.Install below which contains stdp_guetig_9ml

import nest
nest.Install("mymodule")
import numpy

import time

nest.ResetKernel()

dt   = 0.01 # [ms]
tsim = 0.5  # [s]

nest.SetStatus([0],{'resolution':dt})

pg  = nest.Create('poisson_generator',1)
nest.SetStatus(pg, {'rate': 10.0})
pre  = nest.Create('parrot_neuron',1)
post = nest.Create('iaf_neuron', 1)
nest.SetStatus(post, {'I_e': 500.0})

nest.Connect(pg, pre, model='static_synapse')
nest.Connect(pre, post, model='stdp_guetig_9ml')

nest.Simulate(1000.0)
